### ISSUE TITLE
Missing rollup config in sample?

### ISSUE THREAD

**Issue by jamiewastin** [dherges/ng-packagr#15]
Taking a look at the [integration/sample/ng-package.json](https://github.com/dherges/ng-packagr/blob/master/integration/sample/ng-package.json#L9) example on master, it references a rollup config file called `rollup-config.js`. However, this file does not exist!

There seems to be two problems here:
 - The sample is incomplete, and should contain `rollup-config.js`
 - The sample doesn't fail the build, despite the fact `rollup-config.js` does not exist.

**Comment by dherges** [comment]
Hi @jamiewastin,

excuse my response time. 

Regarding the rollup-config, please see my remarks in #4: to me, this is a design choice how configs of the "under-the-hood-tooling" should be handled. Due to the complexity, and in view of angular/angular-cli#6510, angular/angular-cli#1692, angular/angular-cli#6446, my decision is to write a tool that takes away burden from library authors. I am taking an opinionated stance with `ng-packagr`: what tools are used "under-the-hood" shouldn't bother library authors. The `ng-package.json` should, at a high level, describe the structure and characteristics of an Angular library. `ng-packagr` will take care to create the right configurations.

With `1.0.0-alpha.3`, the format of `ng-package.json` has changed and there's a JSON schema describing that format. By default, external dependencies from the `@angular/*` packages and `rxjs` are correctly mapped in the rollup config. It will be possible to provide additonal "external" dependencies in the [`lib.externals` property](https://github.com/dherges/ng-packagr/blob/master/ng-package.schema.json#L40-L43) – this feature still needs to be implemented. The old `ngc.tsconfig` and `rollup.config` properties will be dropped.

If you like to, feel free to open a PR!

Cheers! 🍻
