### ISSUE TITLE
When to use secondary entry points / sub-packages vs. multiple packages

### ISSUE THREAD

**Issue by jbeckton** [dherges/ng-packagr#199]
My library does not currently have any primary entry modules

@mylib/auth
@mylib/ui
etc...

How can I get around the required primary entry? currently I get an error "public_api.ts' is not a module." unless I have something exported from the primary entry.

**Comment by DavidParks8** [comment]
There is a known bug in 1.5.0-rc.0 that's documented by #189 and fixed by [this PR](https://github.com/dherges/ng-packagr/pull/198). Once merged and released, you should be able to customize secondary entry files.

**Comment by DavidParks8** [comment]
Also, if you have no primary entry files, then perhaps that means many files should be a secondary entrypoint. This would not be unheard of because that is similar to what @angular/materal2 does. Their solution is to make every component have it's own, separate module.

**Comment by dherges** [comment]
Hi,

Thanks for reporting!

If understand correct, you’d like to have only secondary entries (sub-packages) and a “shallow” package.json for the npm package. This is an use case which currently is not supported afaik. It would also mean that users if the lib can never “import .. from ‘@org/lib’” but neeed to import individual sub packages “.. from ‘@org/lib/a’”, “.. from @org/lib/b’” and so on

Can you respond whether this is what you like to do? If yes, I will keep this issue as ab feature request / enhancement.

Cheers, David

**Comment by jbeckton** [comment]
I see, so I should look at my library as a set of libraries contained within a single package.

@my/lib1
@my/lib2
@my/lib3

makes better sense I guess.

Thanks!

**Comment by jbeckton** [comment]
@dherges One last question.

Having multiple primary entries do I need a package.json for each? if so how does one package/lib import another? I may have modules in one library that need to be reused in another.

**Comment by dherges** [comment]
@jbeckton Yes, you then have 3 package.json files, one for each lib, i.e.:

```
|- a
   |- package.json
|- b
   |- package.json
|- c
   |- package.json
```

You will also write the outputs for each lib to a separate folder, e.g. `dist/@org/a`, `dist/@org/b`, `dist/@org/c`.

I would symlink `node_modules/@org/a` to `dist/@org/a` and let ng-packagr generate write the output to that dist directory. You need to make sure that the build order is in the right order, for example: if `@org/b` depends on `@org/c`, you need to build `@org/c` first - the build order could be: `@org/a`, `@org/c`, `@org/b`.

**Comment by dherges** [comment]
changed title and labelled this issue, so that others maybe find it more helpful.

**Comment by jbeckton** [comment]
@dherges That sounds a bit complex, I am leaving this project with a client when i am done so I need to keep it simple. I guess the secondary entries is going to be easier but it seems like the tooling breaks when I do that, it does not like the empty package.json unless my lib is inside the src/app directory. I am trying to keep the sandbox app and the lib code separate.

**Comment by deebloo** [comment]
Yeah you will have to use npm link to make this work. I wrote a small script that does all of it for me. Perhaps you could do the same for your client?

**Comment by deebloo** [comment]
I am actually giving a talk on this next week. When my sample repo is done I can share it

**Comment by jbeckton** [comment]
@deebloo thanks, I'll check it out. Most likely I will revert back to the way I have built libraries prior to discovering ng-packagr.

**Comment by dherges** [comment]
If there are no more questions, i close the issue now. It's labelled and kept as "documentation".

Should there be more questions or ideas to this, please comment and/or re-open!

**Comment by kuhnroyal** [comment]
I ran into the of multiple entry points and managed to solve this by adapting my npm scripts like this.

```json
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "yarn build:lib && ng build",
    "build:lib": "yarn build:lib/1 && yarn build:lib/2",
    "build:lib/1": "rimraf dist/lib/1 && ng-packagr -p lib/1/ng-package.json",
    "build:lib/2": "rimraf dist/lib/2 && ng-packagr -p lib/2/ng-package.json"
  }
```

**Comment by mauriziocescon** [comment]
Hi! 

In one of my projects, I have the same configuration described by @jbeckton ([here is my poc]( https://github.com/mauriziocescon/ngrx-app/tree/custom-blocks)). 
```
|- modules
    |- shared
        |- package.json
    |- core
        |- package.json
     .... 
```
In particular, `core` needs to import `shared`. I followed the configurations from [ng-packagr angular-cli example](https://github.com/dherges/ng-packagedI'm) and I tried to use [lerna ](https://github.com/lerna/lerna) in order to establish links between modules. 

But I got errors: ` error TS2307: Cannot find module '@app/shared'` during core building! 

My scripts (main package.json): 

```
"build:app": "lerna bootstrap && cpr dist/core src/@app/core && ... && cpr dist/shared src/@app/shared && ng build --app packages && rimraf src/@app",
"build:modules": "lerna bootstrap && rimraf dist && lerna run build",
```

with core package.json

```
{
  "name": "@app/core",
  "version": "1.0.0",
  "scripts": {
    "build": "ng-packagr -p package.json"
  },
  "devDependencies": {
    "@app/shared": "1.0.0"
  },
  "peerDependencies": {
     ...
  },
  "ngPackage": {
    "$schema": "./node_modules/ng-packagr/package.schema.json",
    "dest": "dist/core",
    "workingDirectory": "../.ng_build",
    "lib": {
      "entryFile": "public_api.ts",
      "cssUrl": "inline",
      "sassIncludePaths": ["./src/assets/stylesheets"]
    },
    "dest": "../dist/core"
  }
}
```
and shared
```
{
  "name": "@app/shared",
  "version": "1.0.0",
  "scripts": {
    "build": "ng-packagr -p package.json"
  },
  "devDependencies": {
  },
  "peerDependencies": {
     ...
  },
  "ngPackage": {
    "$schema": "./node_modules/ng-packagr/package.schema.json",
    "dest": "dist/shared",
    "workingDirectory": "../.ng_build",
    "lib": {
      "entryFile": "public_api.ts",
      "cssUrl": "inline",
      "sassIncludePaths": ["./src/assets/stylesheets"]
    },
    "dest": "../dist/shared"
  }
}
```

Any idea what's going wrong? 

Thank you very much!

**Comment by JrPribs** [comment]
@dherges @DavidParks8 I am running into an issue with regards to ordering of package builds when using`@angular/cli` 6+ and a material like file structure. I can get everything to build and package fine, but since some of the packages are dependent on each other when consuming the library I get errors saying one of the packages is missing (since it was compiled after the one consuming it)

Normally after generating a library via cli builds are run with just `ng build --prod` which points to `@angular-devkit/build-ng-packagr:build` which seems to iterate through the directory structure and is only ordered by the existence of packages in the "dependencies" property of the package.json (thats what I gathered from looking through devkit anyway perhaps Im way off there). I have a material like lib structure so requiring a package to itself via dependencies seems strange.

Is there anyway to control ordering when using `@angular/cli`? It would be great to have a build order prop in the packagr schema, but not sure if that is inline with the packages vision.

I also tried calling `ng-packagr` directly from the cli to build the packages in order manually but it seems I can't get it to run. whenever I run ng-packagr manually I get an error regarding `@angular/compiler-cli/src/perform_compile`.

Let me know if you need anymore info, or if perhaps I should more this over to cli project. I thought this issue would be a good place to start since it's relevant and this will provide a sort of update to the doc issue.

**Comment by JrPribs** [comment]
So it seems my issue was actually related to 2 different things, the missing module errors seemed to stem from the fact that my "primary" module was in the main directory while the rest of the modules were in subdirectories. when I moved the primary module to a subdirectory and pointed the main package.json ngPackagr entry file into that folder it seemed to build in the proper order. 

Once that was resolved I was still getting this error:
```
Module not found: Error: Can't resolve '@org/ngx-dart/auth/services/auth-endpoints/index' in '/Users/john.pribesh/code/org-web-app/src/app/auth'
```
This error seemed to be related to the fact that I was trying to connect a couple nested index files to export each directory, and not directly exporting my services from the main public_api.ts file for that directory. Once I made the following change things seem to be working now:

```
export * from `/services`;
```
(when using the above I had barrel files in each subdirectory)
to
```
export * from `./services/auth-endpoints/auth-endpoints.service';
```

**Comment by matheo** [comment]
@dherges Looking at `ng-packaged` I saw three independent libraries. Is it possible to setup and build libraries that depend on each other? I imagine I would need to install the library on the same `nx` project so it gets detected as an external dependency but that won't work for `ci` tests.
Any option to define a path to the compiled lib? Thanks in advice!

**Comment by pycraft114** [comment]
@DavidParks8  So what does angular-material2 exactly export at primary entry file? ``` This is so that developers can import all material modules from @angular/materal without having to know about the internal path structure of the library, and is required to meet the angular package format proposed by google.``` if then, aren't they exporting all material modules at primary entry file?

**Comment by DavidParks8** [comment]
@pycraft114, what they export can be found in their [`public-api.ts`](https://github.com/angular/material2/blob/master/src/lib/public-api.ts) file. Notice that they are exporting all the material modules in the same folder and sub-folders. So you are correct.

**Comment by patrickmichalina** [comment]
This is particularly challenging when writing Browser/Server (Universal) modules that have common services but separate modules. They get bundled together even though they should be separate outputs.
