### ISSUE TITLE
Support sass import files

### ISSUE THREAD

**Issue by pjpenast** [dherges/ng-packagr#21]
Hello, in my library I have sass files and I can not compile with ng-package since it does not seem to support them when you have imports from other sass files:

My error: 

```
 formatted: Error: File to import not found or unreadable: ../../../node_modules/@stratio/egeo-ui-base/utils/typography.
       Parent style sheet: /home/pjpena/Documentos/projects/egeo/egeo/src/lib/st-radio-menu/st-radio-menu.component.scss
        on line 1 of src/lib/st-radio-menu/st-radio-menu.component.scss
>> @import '../../../node_modules/@stratio/egeo-ui-base/utils/typography';
```

**Comment by dherges** [comment]
Thanks for your feedback!

Can you give me a repro? Since I have a working example on my machine, I cannot trace back the issue.

**Comment by pjpenast** [comment]
You can see the error in my fork of the library that we are developing:

https://github.com/pjpenast/egeo

Branch feature/ng-packager

And run the script npm run build:pack

Thanks!!

**Comment by dherges** [comment]
@pjpenast I think it's happening because `ng-package.json` points to the root folder of your project and then it copies over any `**/*.ts` files trying to inline. Please try [setting `src` folder](https://github.com/dherges/ng-packagr/blob/master/lib/ng-package.schema.json#L11-L15).

btw, the `.ng_build` shouldn't be checked in.

**Comment by pjpenast** [comment]
Thanks for the help!
