### ISSUE TITLE
How to include common css rules in library code after packaging

### ISSUE THREAD

**Issue by Abhishek-Kanitkar** [dherges/ng-packagr#216]
## Type of Issue

```
[y ] Bug Report
[ ] Feature Request
```

## Description

I have created an angular cli project for creating library. I installed ng-packagr.
I have a few css rules that are common to all components in my library.

But they don't get included in final packed version of my library.

How to achieve this ?

#### How To Reproduce

If you keep any css rules as common in app.component.html for example, then after you npm install library into another project, you don't see those common css rules available.

#### Expected Behaviour

One should be able to have common css rules in library for all components.

#### Version Information

```
ng-packagr: v1.4.1
node: v6.11.3
@angular: v4.x.y
rxjs:
zone.js:
```

_please include any version information that might be relevant, e.g. other third-party libraries_

**Comment by DavidParks8** [comment]
Have you looked at setting component view encapsulation to `ViewEncapsulation.None`? Material2 uses that to allow simpler style overrides. That will disable the shadow dom behavior in the component scope, and allow css to permeate more than a single component. Otherwise, you can always copy a css file to your library as a step external to ng-packagr.

**Comment by Abhishek-Kanitkar** [comment]
Thanks David !

I have already set ViewEncapsulation.
But the problem is style.css doesn't get copied over to dist, after packaging. Only component's css file is getting copied over.

Is that expected? 

Should I copy the compiled and compressed .css file which contains common styles for all components over to dist on my own ?

Is that not supported out of the box by ng-packagr?

**Comment by DavidParks8** [comment]
Correct, that is not supported out of the box. Ng-packagr tries to be as unopinionated as possible. Since there is no standard for the location and format of external styles, it’s hard to implement such a feature without taking a stance on the matter. As of right now, the way to achieve what you want would be to copy the css files yourself.

**Comment by dherges** [comment]
@Abhishek-Kanitkar Yes, "static" assets like a global stylesheet, images, and resource which are **NOT INLINED** in the JavaScript bundles need to be handled in a separate step.

Please see #123
