### ISSUE TITLE
Write artefacts to harmonized `dist` folder layout independent of `entryFile` location

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#23]
@angular/core folder layout:

```
- public_api.ts
- src/
   |- core.module.ts
   |- foo.ts
   |- ...
```

other folder layout:

```
src/
  |- public_api.ts
  |- ui-lib.module.ts
  |- foo.ts
```

Support that both file layouts result in a `<dist>/src` folder being created

**Comment by about-code** [comment]
Hi once again a question: what's the matter with `public_api.ts`? Hasn't there been a convention for TS-Libs that a package's public API should be exported by `index.ts`? FWIW TypeScript module resolution has even been implemented to be able to automatically detect `index.ts` or `index.d.ts` files in NPM packages. I guess if there's yet another `public_api.ts`, `index.ts` would just re-export anything from `public_api.ts`. Therefore I wonder why angular community moves towards `public_api.ts`.

Is it just to indicate an intent and make people more aware of paying attention to what's private or public or is `index.ts` meant to export more than just `public_api.ts`? The latter wouldn't make sense to me, though.

**Comment by dherges** [comment]
@about-code the `public_api.ts` "pattern" goes down to Angular's "Flat ECMAScript Modules" idea. It needs an entry file that references all symbols of a lib and then creates a so-called "flat-module file" (configured somewhere down the toolchain w/ `ngc`) for the imports. I think jason Aden talks about this: https://www.youtube.com/watch?v=unICbsPGFIA&feature=youtu.be

**Comment by about-code** [comment]
David, thank you for the link. Jason gave a good talk which helped me packaging a lib prior to evaluating *ng-packagr*. However, I couldn't find a hint on why feeding a `public_api.ts` to `ngc` is beneficial over `index.ts`.

@jasonaden would you mind elaborate on what the reasons are to export a library's API via an extra `public_api.ts` instead of doing it via an `index.ts` on the root of a package? Is it a *proposed* pattern or an Angular-internal convention [Material2](https://github.com/angular/material2) seems to completely omit `index.ts` while [`@angular/core/index.ts`](https://github.com/angular/angular/blob/master/packages/core/index.ts) just re-exports `public_api.ts`.

I understand that the repository layout of a lib doesn't matter as much when a consumer installs and consumes the version published to npm. But for mono-repos where individual packages might not be published from the beginning but rather consumed from their unbuilt source structure (untill they are ready to be published) I think it would be much easier to point TypeScript to the `packages` folder and let the TypeScript resolution algorithm explore the library exports by looking for `index.ts` files rather than having to configure each individual package with a `typings` key in the package's `package.json` or with a a separate entry in the repository's `tsconfig.json`.

I am thinking of a mono-repo structure like
```
${PROJECT_HOME}
      |
      |- packages/
      |      |- foo/
      |      |    |- src/
      |      |    |    |- ...
      |      |    |- package.json
      |      |    |- index.ts
      |      |...
      |- tsconfig.json
      |- gulpfile.json
```

**Comment by dherges** [comment]
Solved by #184

**Comment by jasonaden** [comment]
@about-code Sorry, I missed your comment earlier.

The reason we use public_api.ts is that we use the `angularCompilerOptions` option in `tsconfig.json` to output an `index.ts`. So what happens in the Angular project is the `index.ts` file is there only for the editor. The compiler generates an `index.js` file that has nothing to do with the `index.ts` file in sources.

cc @dherges

**Comment by about-code** [comment]
@jasonaden  No problem. Thank you for your explanation.
