### ISSUE TITLE
packaging when third party angular library is imported fails.

### ISSUE THREAD

**Issue by sbibek** [dherges/ng-packagr#237]
Packaging with module with no third party dependency passes but fails when third party module is imported.

**Comment by ttomoday** [comment]
I have the same problem.
There is an error when importing 3rd party module.

```cmd
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

Already tried increasing --max_old_space_size, but didn't help.

**Comment by KyleMcNutt** [comment]
@sbibek Usually, you want to include 3rd party libs in the `externals` property of your `ng-package.json`. See [here](https://github.com/dherges/ng-packagr/issues/142) as an example.

3rd party libs are sometimes in the CommonJS format, which Rollup doesn't support very well. The way around this would be to use the `namedExports` property of the Rollup CommonJS plugin, but ng-packagr doesn't expose this property (by design).

Instead, you can set the 3rd party lib to be external of your bundle, and then set it as a peer dependency in your package.json. Then when someone consumes your library, they will also need to include that 3rd party library, and your library should work.

This also gives the advantage that it makes sure that your consumers aren't accidentally bundling something twice in their project. For example, if you included a 3rd party library, and they also included the same 3rd party library directly, then they could be shipping that library twice, and not know it.

@ttomoday I've never seen a heap out of memory error before when bundling 3rd party libraries, but it could be that you're trying to bundle _a lot_ of 3rd party libraries. Possibly `externals` would also fix your issue.

**Comment by ttomoday** [comment]
@KyleMcNutt Thanks a lot. that fixed issue with building the package.

But then when importing this in another project i get an error 
```cmd
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported funct
ion (position 194:50 in the original .ts file), resolving symbol NgModule ...
```

I've found that it can happen when module has no metadata, but ng-packagr adds it automatically.

Don't you know what can cause the problem ?

**Comment by KyleMcNutt** [comment]
@ttomoday Hmm.. not sure here. My only guess is to make sure you have the 3rd party library in your dependencies of the project you're importing your library into.

**Comment by dherges** [comment]
Hi @sbibek and @ttomoday,

#129 is a collection of questions and known issues around third party dependencies.

Please check if your situation is described and answered there. Should you have a concrete issue, please open a dedicated issue!
