### ISSUE TITLE
package.json in output is compressed

### ISSUE THREAD

**Issue by e-cloud** [dherges/ng-packagr#257]
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

package.json in output is compressed

#### How To Reproduce

use the [ng-packaged](https://github.com/dherges/ng-packaged) and install the latest ng-packagr to perform packaging.

#### Expected Behaviour

no compressed for package.json

#### Version Information

```
ng-packagr: v1.5.0
node: v8.9
@angular: v5.0.0
```

**Comment by dherges** [comment]
Hi @e-cloud,

what do you mean by compressed? There is no whitespace and line breaks?

**Comment by e-cloud** [comment]
@dherges, yes.

**Comment by kylecordes** [comment]
It's often helpful to inspect this output, and the size savings from having it in a single line with no white space is very minor. I think it is an excellent idea to emit this in a pretty printed form.

I further suggest something like:

https://github.com/substack/json-stable-stringify

So that there are not needless changes to the output from one run to another, from one machine to another. These new this changes will happen if using the built-in JSON.stringify.
