### ISSUE TITLE
Minify JavaScript bundles

### ISSUE THREAD

**Issue by jackjoy** [dherges/ng-packagr#3]
I'd like to see this feature be implemented in future release.

**Comment by dherges** [comment]
Hi @jackjoy,

please excuse my response time.

This is a matter of adding [rollup-plugin-uglify](https://github.com/TrySound/rollup-plugin-uglify) to the build steps performed by rollup, or [uglify-js](https://github.com/mishoo/UglifyJS2), [uglify-es](https://github.com/mishoo/UglifyJS2/tree/harmony) as an additional build step.

It's not a top priority to me, since most applications will likely use webpack or another module bundler to minify dependencies in their production bundles.

If you like, you can open a PR anytime! It's welcome!

Cheers! 🍻

**Comment by wallace41290** [comment]
I feel this will be a very useful feature. When I run my angular application that depends on a component library created with ng-packager the vendor bundle is HUGE. Serving an empty CLI project generates a vendor bundle of 2.53MB, and if I import the modules from my ng-packagr library it goes up to 7.55MB and takes about 120 seconds to recompile everytime I make a change.

I have verified that when I do a ng-build with --prod and --aot the size goes way down, but the enormous size makes it very painful while developing. In comparison when I import Material2's component library the vendor bundle size is 4.21MB. When I import both Material2 and my ng-packagr library it goes up to 9.03MB.

Is there something I am doing wrong which causes such large vendor bundles or would minified bundles solve my issues?

**Comment by DavidParks8** [comment]
Minified bundles will probably not help you since the Angular CLI should resolve your library from flat modules, not bundles. Is the library you are using available publicly so we can help troubleshoot?

**Comment by Ks89** [comment]
This is very useful when you want to share live examples of your library on plunkr.

**Comment by deebloo** [comment]
I see there is already a PR for this but the other argument for doing this is it is specified in the folder layout diagram for the Angular package format
