### ISSUE TITLE
should a lib be able to use another lib from the same monorepo ?

### ISSUE THREAD

**Issue by loicsalou** [dherges/ng-packagr#320]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

either I made a mistake, or it is currently not possible what I'm trying to do:
- I use nrwl/nx and I followed ng-packaged example, so I'm working in a monorepo
- I built one demo app and 4 libs
- first lib is named "shared" and contains generic tools, like Message definition, services common to every feature in my apps etc. This shared module is used in a second lib.
- It seems that a lib can't consume another lib, ng-packagr fails and error is "Cannot find module '@nx-component-lib/shared'". I built the shared lib first so as to be sure it exists.

#### How To Reproduce

I suppose that any lib using another lib should face the same issue. I can create and give a repo if you tell me that what I'm trying to achieve is possible.

#### Expected Behaviour

a library created in a mono repo should be able to use another library created in the same monorepo.

#### Version Information

```
ng-packagr: v1.6.0
node: v8.4.0
@angular: v5.0.0
rxjs: ^5.5.2
zone.js: ^0.8.14
```

I'm also using primeng (latest), lodash, barcoder, checkdigit, bootstrap and font-.awesome

**Comment by about-code** [comment]
I have only superficial knowledge of Nrwl/nx but I could imagine the problem here is that ng-packagr doesn't know (and shouldn't know) about the particular repo setup of Nrwl/nx and where to find packages there. I guess it can't resolve packages outside *node_modules*. So you probably would need shared lib in `node_modules` before building libs depending on it.

To test my hypothesis you could try to copy *shared* lib manually to *node_modules* and see if it can be found by ng-packagr, then.

**Comment by loicsalou** [comment]
nice hypothesis, indeed, it works after copying directory "@nx-component-lib" directory to node_modules, thanks !
However if I compare with how maven behaves with java libs, there's something missing.
I definitely think something is missing there. Maybe it's a bit complicated though to build libs in the correct order (I specified in my dependent lib that this lib depends on the shared lib so I think dependency information is there).

Thanks anyway I can handle this for now.

**Comment by about-code** [comment]
@loicsalou Glad I could help you. I am still wondering why you have to copy it at all because I would expect Nrwl/nx to have configured its module bundler to not just look into *node_modules* but also into *libs*. But  I'm afraid without a repro or more information of your situation I can't help out more. 

Note that there's currently a [limitation](https://github.com/nrwl/nx/issues/87) in Nrwl/nx with respect to scoped packages but if *nx-component-lib* is your Nrwl-workspace name then it might not affect you. Otherwise if you have created an `@nx-component-lib` inside of Nrwl's `lib` folder then that could be part of the problem.

**Comment by BeaveArony** [comment]
I currently have a lib in nrwl/nx consisting out of 4 libs. I build them in the right order and copy them to the node_modules folder, one by one. It works, but the app has to import all 4 packages now and I even need a forRoot() to share the services between them.

I wonder if there is a way to bundle them so the consumer could just import @my/lib instead of @my/lib1, @my/lib2 ...?
