### ISSUE TITLE
Run unit tests from ng-packagr command

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#5]
If integrated into `ng-packagr`, it will be in an opinionated way. It will look like this:

The tool chain will be _plain-old Angular testing_: karma, webpack, jasmine, istanbul

- `myfoo.ts`
- `myfoo.spec.ts` (right next to the comp, service, whatever being tested)
- `**/*.spec.ts` will be excluded from `build` task
- an auto-generated `run-tests.js` will include all spec files
   -  `var testContext = require.context(`${opt.src}`, true, /\.spec\.ts/);` 
- `karma.conf.js` will be auto-generated
- `webpack.test.js` will be auto-generated
- test runs will report: lcovonly, json, html (all written to disk). coverage report (html and json written to disk). coverage report to stdout (for the infamous gitlab stuff, still needs to be discussed, since GitLab users could simply pick up the json files and print to stdout with [istanbul-combine](jamestalmage/istanbul-combine))

**Comment by dherges** [comment]
Implementing testing, will arise the need for "commands" in ng-packagr. Usage should be:

```
$ ng-packagr -p ng-package.json           ### default build command
$ ng-packagr build -p ng-package.json  ### build command
$ ng-packagr test -p ng-package.json    ### test command (run tests once)
```

to be discussed: "watch mode" for local dev, "headless" runners for CI (phantom, ChromeTravisCI, or something else?)

```
$ ng-packagr test:dev -p ng-package.json    ### test command for local dev (watch mode)
```

One idea: describe different test "profiles" (profiles is not a good word ... maybe "premises", "spots"? ... "environment" and "target" are also used veeeeery often).

- `test:dev`: Chrome browser, watch mode
- `test:ci`: 'ChromeTravisCi', phantom as fallback, run once
- `test`: auto-detect or auto-configure best matching premise

Then, maybe allow users to set "premises" in `ng-package.json`:

```json
  "test": {
    "premises": {
       "dev": {
         "browser": "Chrome",
         "watch": true
       },
       "ci": {
         "browser": "Phantom",
         "watch": false
       },
    }
  }
```

**Comment by about-code** [comment]
Congratulations @dherges. I tried *ng-packagr* yesterday and its an excellent tool and absolutely easy to set up. It did exactly what I expected it to do. I am very happy to read (e.g. in #65) that you are focused and don't plan to make it the next best swiss-army-knife-cli. I really appreciate and share such mindset. :+1: 

After having read this thread, though, and that you'd be willing to introduce support for unit testing and cli-like commands I asked myself if I would expect that from the tool. Spec files aren't part of the distributed bundles and thus could actually be completely ignored by a packager/bundler. From that reasoning I came to conclude that I would probably consider anything which has to do with those files out of scope. I admit this might be kind of a fundamentalistic point of view and who am I to judge the plans for your project. I just thought to give you some feedback and start a discussion.

Part of why I am a little skeptic is, I am afraid that once this feature is implemented I need to pull in all these thousands of transitive dependencies of karma, webpack, jasmine etc. in order to enjoy *ng-packagr*. I am really interested to learn about your rationale and what your plans for *ng-packagr* are. Have you thought of implementing unit test support kind of like a separate *ng-packagr-testing-plugin* which is opt-in for anyone who has demand for a testing utility?

Thanks anyway. :heart:

**Comment by dherges** [comment]
@about-code Uh, I like the idea of a separate `ng-packagr-testing` utility!

Maybe it's a nice idea to build a "multi-module" project e.g. w/ yarn workspaces for ng-packagr and then publish multiple npm packages as coexistent releases (same version number, et al).

**Comment by about-code** [comment]
> Maybe it's a nice idea to build a "multi-module" project e.g. w/ yarn workspaces for ng-packagr and then publish multiple npm packages as coexistent releases (same version number, et al).

I don't know yarn workspaces and would have thought of [Lerna](https://lernajs.io/) first, but if they are easier to manage, then yeah, it could be a very nice approach.

**Comment by dherges** [comment]
Deprioritized this feature. Auto-generating the `karma.conf.js` is probably not a good idea. IntelliJ (and other IDEs) have first-class support for Karma but need to locate that `karma.conf.js` file in the project.

Will need to elaborate how to use testing in libs w/ minimal configuration. Using the `@angular/cli/plugins/karma` removes the additional webpack config but it needs the `.angular-cli.json` to work. A custom angular karma plugin that works w/ the above folder layout would be a good idea.

Rough draft idea: `karma.conf.js` + `test.ts`

```js
module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', 'angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-angular-testing-plugin')
    ]
  });
};
```

Maybe there is already an existing solution?

**Comment by dherges** [comment]
Changed to **"WONTFIX"**

Motivation: existing tool support requires a `karma.conf.js` to work. For example, IntelliJ has good Karma support. See above. Goal should imho to have an Angular test runner for karma

- a) w/ support for typescript and scss, less, and so on and on and on .... 
- b) run tests against `dist` javascript files
