### ISSUE TITLE
[v2] problems in AOT build for a consumer angular-cli project that consumes a ng-packagd library with ngx-bootstrap & ag-grid

### ISSUE THREAD

**Issue by andrea-spotsoftware** [dherges/ng-packagr#619]
## Type of Issue

```
[ ] Bug Report
[ ] Feature Request
[X] Support 
```

## Description

Hello everyone, I'm having troubles while I'm trying to package my library that uses, among others, **ag-grid** and **ngx-bootstrap** (as dependencies). 
I'm starting a feasibility test-case with an empty seed that is made of:

- src of the library and an **awful** component that uses some of those external libs (it's just a test 😄 );
- demo app that directly links ts files (JIT, running with webpack);
- integration app that consumes the _ng-packagd_ package (created with angular-cli).

everything works fine in: 

- demo (npm start); 
- integration, running (npm run build & cd integration & npm install & ng serve)

Problems starting when using ng serve --aot in integration angular-cli app; build is successful, but I have runtime errors when clicking on show modal:
```
ERROR Error: No component factory found for ModalBackdropComponent. Did you add it to @NgModule.entryComponents?
```
and when clicking on show grid:
```
ERROR Error: StaticInjectorError(AppModule)[Ng2FrameworkFactory -> BaseComponentFactory]: 
  StaticInjectorError(Platform: core)[Ng2FrameworkFactory -> BaseComponentFactory]: 
    NullInjectorError: No provider for BaseComponentFactory!
```

#### How To Reproduce

The code is in this repository: https://github.com/andrea-spotsoftware/ng-library-seed
```
npm install
npm run build
cd integration
npm run update-lib

ng serve (everything working)
ng serve --aot (not working)
```
#### Expected Behaviour

Should work good in aot?

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr:            2.0.0
@angular/compiler:     5.2.5
@angular/compiler-cli: 5.2.5
rollup:                0.55.5
tsickle:               0.26.0
typescript:            2.5.1
```

ngx-bootstrap: 2.0.2
ag-grid: 16.0.0

**Comment by NoNameProvided** [comment]
The error is pretty self-explanatory, you need to add the component you want to show in your modal to the `entryComponents` array, otherwise, Angular won't know you want to inject that at runtime and won't create a factory for it. So just add your `ModalBackdropComponent` to the list ([here][1]) and it should work. 

The second also explains itself, `BaseComponentFactory` is not provided add the module which exports it should be added to the `provider` array. So you need to create the `provider` key [here][2] and add the correct module.

Btw your app is not runnable because you reference a local package (`"@spot/infrastructure": "file:../dist"`)

[1]: https://github.com/andrea-spotsoftware/ng-library-seed/blob/c53f940ae1cb14c7f4cda5f029a8f58e5355937a/integration/src/app/app.module.ts#L12
[2]: https://github.com/andrea-spotsoftware/ng-library-seed/blob/c53f940ae1cb14c7f4cda5f029a8f58e5355937a/integration/src/app/app.module.ts#L19

**Comment by andrea-spotsoftware** [comment]
@NoNameProvided thank you for response, but [ModalBackdropComponent ](https://github.com/valor-software/ngx-bootstrap/blob/d8d280345f24a7da42cd6063d61811970b8746b1/src/modal/modal-backdrop.component.ts) is not mine, it's a component provided by ngx-bootstrap, same thing for [BaseComponentFactory](https://github.com/ag-grid/ag-grid-angular/blob/master/src/baseComponentFactory.ts), that is a service provided by ag-grid angular. 
I think they should be resolved without re-declaring or re-providing them in my lib, right?

My app should run if you follow the instructions:
```
npm run build (generate the dist)
cd integration
npm run update-lib (installs the local referenced @spot/infrastructure from dist)

ng serve (everything working)
ng serve --aot (not working)
```

**Comment by andrea-spotsoftware** [comment]
Update: now everything is working fine.

What i changed? In my initial library package.json file, i added as **dependencies** some packages, including ag-grid. Now i moved everything to **peerDependencies** and it's working like a charm.

Can someone explane me why? @dherges
