### ISSUE TITLE
Provide option to keep the dist folder

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#632]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description
At the moment with every build the destination folder for the distributed is deleted. Which make it almost impossible to create a watch using ng-packagr. As the `npm link` will be lost when the `dist` folder is deleted, and thus you'll end up with webpack giving a error that the module cannot be resolved.

@dherges, if you are okay with implementing this, I can do this feature :)

#### How To Reproduce

- Link a library built with `ng-packagr` ie the dist folder and run a build using `angular-cli` or any other build system

- Re build the library with ng-packagr

#### Expected Behaviour
No error

```
ng-packagr: 2.0.0
```

**Comment by dherges** [comment]
Yes, sure. How will you going to solve it? Keep the folder and truncate its content?

Otherwise it may signal the need for more commands like `ng-packagr clean`, `ng-packagr build`, ...

**Comment by alan-agius4** [comment]
Actually I think truncating the content will still cause an error in Webpack. I need to reconfirm this though. 

My initial idea was to actually just override the files when this option is true.

**Comment by alan-agius4** [comment]
Following, what I mentioned yesterday I did some digging into it and `webpack` doesn't actually trigger a build when a new file is added, but rather than the contents of the file has changed.

So truncating the a folder contents and than copying them won't trigger a build.

I'll open an issue with Webpack maybe it's a bug or there is an option to enable this somehow.

**Comment by JanneHarju** [comment]
I would like to have this also. My scenario is to run concurrenlty ng build --watch with scss-bundle with -w parameter. But because ng-packagr is always removing dist folder I must use wait-on and wait that librarys main d.ts file is generated and after that I start scss-bundle with -w parameter. If I don't wait that main file, my scss-bundle file would be removed also. This scenario also reguires me to clean dist folder before everything. So it is like this: "clean dist" && concurrently "ng build --watch" "scss-bundle some-parameters-here -w folder". By adding wait-on && before scss-bundle I can handle the initial dist clean which would clean my scss-bundle file. But if I could disable initial clean I could remove that wait-on on clean my build process a bit. Same kind of parameter is also in angular cli with basic application so you should ask how they have done https://github.com/angular/angular-cli/wiki/build --delete-output-path
