### ISSUE TITLE
feat: peerDependencies and devDependencies auto whitelist.

### ISSUE THREAD

**Issue by alan-agius4** [dherges/ng-packagr#716]
## Type of Issue

```
[ ] Bug Report
[X] Feature Request
```

## Description
At the moment If I have a `package.json` like this;
```json
 "peerDependencies": {
    "rxjs": "^5.5.2"
  },
  "devDependencies": {
    "rxjs": "^5.5.2"
  }
```

I'll get an error `Distributing npm packages with 'devDependencies' is not recommended. Please consider adding rxjs to 'peerDepenencies' or remove it from 'devDependencies'.`
on/consumers/ng-cli)!_

For development you cannot use `peerDependencies` as these don't get installed. I'd expect that if the `devDependencies` is listed in the `peerDependencies` I don't need to add it explicitly in the whitelist. It's whitelisted automatically.

#### Expected Behaviour
No error.

#### Version Information
```
ng-packagr: 2.3.0
```

_Please include all version numbers that might be relevant, e.g. third-party libraries_

**Comment by codegagan** [comment]
I took the latest  "ng-packagr": "^2.4.1" , How can I whitelist the dependencies manually to remove the errors/warnings ?

**Comment by alan-agius4** [comment]
@codegagan you can remove the warnings by adding the below to `ng-packagr.json`, right next to `lib` property.

```json
whitelistedNonPeerDependencies: ["angular"] // note: this will be matches as a regexp
```

If you want to turn off this feature you can do the below;

```json
whitelistedNonPeerDependencies: ["."]
```

**Comment by jvanharn** [comment]
That is pretty important documentation, maybe add it to the readme and/or changelog?

**Comment by skaughtx0r** [comment]
@alan-agius4 Actually it needs to be added next to `"ngPackage"`, not `"lib"`

```
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
  "ngPackage": {
    "lib": {
      "entryFile": "public_api.ts"
    }
  },
  "whitelistedNonPeerDependencies": [
    "angular"
  ]
}
```

**Comment by alan-agius4** [comment]
@skaughtx0r, `ngPackage` doesn't form part of a valid schema:

You config should be:
```json
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
   "lib": {
      "entryFile": "public_api.ts"
   },
  "whitelistedNonPeerDependencies": [
    "angular"
  ]
}
```

**Comment by alan-agius4** [comment]
@skaughtx0r, it depends if you are using it in `package.json` or not. 

If you are using it in a `ng-package.json`, `ngPackage` is not a valid property, If you are using it in `package.json` it should be under `ngPackage`

If you are using it in `ng-package.json` it should be 
You config should be:
```js
{
  "$schema": "./node_modules/ng-packagr/package.schema.json",
   "lib": { // this is not required as `public_api.ts` is the default
      "entryFile": "public_api.ts"
   },
  "whitelistedNonPeerDependencies": [
    "angular"
  ]
}
```

**Comment by skaughtx0r** [comment]
@alan-agius4 Oh! Thanks, looks like I'm doing it wrong. I'm using an ng-package.json, I'll need to remove that "ngPackage" attribute.

**Comment by DeveloperAlex** [comment]
Thanks @alan-agius4!  It worked for me.
I added `"whitelistedNonPeerDependencies": ["."]` to my ng-package.json file:

`
{
    "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
    "whitelistedNonPeerDependencies": ["."],
    "lib": {
      "entryFile": "public_api.ts",
      "externals": {
      }
    }
}
`

**Comment by cgatian** [comment]
This should probably be added to the README

**Comment by crysislinux** [comment]
Is there a clear rule about what should go to `dependencies` and what should go to `peerDependencies `? Some packages maybe better be put in `dependencies` because they are more likely to only be used by the package but not the main app.  It probably more a npm problem but I am always not sure about what to do here.

**Comment by phenomnomnominal** [comment]
This seems really heavy handed? I can see having the check for `@angular/*` and maybe `rxjs` and `zone` or something, but other than I'm not sure I see the worth?

**Comment by eliellis** [comment]
#687 has a little more information to clarify.

I'm still not entirely certain of the proper way to set-up the dependencies in a project that has its own internal dependencies apart from run-of-the-mill @angular packages. Further clarification regarding best-practices in this case would be greatly appreciated.

**Comment by alan-agius4** [comment]
If you are building a library, in very rare cases, one should use `dependencies`. As you don't know what the consumer is using. 

Also, if you could share your config I can surly help you out.

**Comment by cormacrelf** [comment]
@alan-agius4 I was using the javascript API-based workaround for JSDoc @ comments in #485. I added the whitelist in the ng-package.json but apparently it still read from package.json, which was still half-configured, so I didn't notice. It works now.

My use case is for https://github.com/cormacrelf/angular-skyhook -- it basically wraps `dnd-core` with angular-specific goodness. `dnd-core` is not user-facing. Most people who have used it don't know it exists. Is this a rare case? No -- it is a very common case of integrating a generic library into the Angular component/module system. And it took me, who used to roll my own build system, a significant amount of time to figure out.

Basically, this is why the whitelist is bad:

* The whitelisting step creates huge walls of red, strange error messages and some googling in a basic use case which should be easy.
* The problem created by whitelisting is difficult to solve. It's not in the README. You'd have to search the GH issues or literally read the JSON schema.
* The regex functionality is unexpected. Usually in js-land people use globs. The instinct to use `@scope/*` would be great, except it would match... `@scope///////////`.
* The inexperienced library authors who were at risk of depending on `@angular/core` are coincidentally the ones most likely to disable the feature entirely out of frustration.
* Altogether, these things mean that instead of a safety net preventing people duping their angular or Rx imports, the feature just makes it way too difficult to use dependencies. It's one of your most popular issues. Is that not a sign?

I can live with disabling `@angular/*` and `rxjs` dependencies, but please make it a blacklist system.

**Comment by alan-agius4** [comment]
@cormacrelf I do agree that glob is better in most of the cases, @dherges what do you think about this?

To address the lack of docs, I create a document about this https://github.com/dherges/ng-packagr/blob/master/docs/dependencies-whitelisting.md

Regarding the blacklist, it's more likely that you want to have `peerDependencies` rather than `dependencies`, And that's why I think a whitelist would be better.  Most of the runtime dependencies that a library has should be as `peerDependencies`, and only in very rare cases these will be as `dependencies`. This is just just about `@angular/*` and `rxjs`. But it goes to all other dependencies, some common I'd day are `date-fns`, `moment`, `hammerjs`, `ionic`, `zone.js`, `lodash` and this list continues...

**Comment by benjamincharity** [comment]
I know this is closed now, but just wanted to throw this opinion out because I think it possibly affects a larger amount of libraries than the maintainers believe.

---

> Most of the runtime dependencies that a library has should be as `peerDependencies`

Definitely agree.

> only in very rare cases these will be as `dependencies`

This is quite subjective IMO. There are many Angular libraries that are simply wrapping another vanilla JS library. While I believe we can all agree that no one should be bundling things like `lodash`, I would say that there are still plenty of times where bundling a resource is a decent choice.

From personal experience, over half of the libraries I've built as OSS or for work should have a bundled dependency (imo).

**Comment by alan-agius4** [comment]
@benjamincharity, fair point and in all fairness no one is stopping you from not having dependencies. It's just that you need to add them to a whitelist which is quite easy.

**Comment by booleanVirus** [comment]
I still have this problem when trying to build the library.
The packager version i use is :  "ng-packagr": "^3.0.0-rc.2".
Even if i try using the above mentioned fixes (whitelisting) i keep on getting this error 
> Dependency 'xxx' must be explicitly whitelisted.

any ideas to why this keeps happening?

**Comment by alan-agius4** [comment]
https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md

**Comment by tommck** [comment]
@dherges Is this still true with recent npm version?  It de-dupes npm packages automatically on install.

I don't see how having things as peerDependencies makes it better.

Here's an example:

I have code shared between Angular and AngularJS.. so, I have a "core" package that is a dependency of both.

The client code (apps) shouldn't have to manually install the "core" package in order to use them, it should just work.

This forces all apps to know about and manually install "core" when installing the framework-specific versions of things.

**Comment by inorganik** [comment]
If you do `ng generate library my-thing` it will generate in `projects/my-thing` it's own package.json with only 2 peer deps:

```
{
  "name": "my-thing",
  "version": "0.0.1",
  "peerDependencies": {
     "@angular/common": "^6.0.0-rc.0 || ^6.0.0",
     "@angular/core": "^6.0.0-rc.0 || ^6.0.0"
   }
}
```

If your lib has a separate dependency, like lodash for example, you would add:

```
  "dependencies": {
    "lodash": "4.17.4"
  }

```
And in the separate `ng-package.json` you would add whitelisted deps and externals like so:

```
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/my-thing",
  "whitelistedNonPeerDependencies": [
    "lodash"
  ],
  "lib": {
    "entryFile": "src/public_api.ts",
    "externals": {
      "lodash": "lodash"
    }
  }
}

```
Hope this helps.

**Comment by joseluisq** [comment]
my `ng-package.json`

```json
{
  "$schema": "./node_modules/ng-packagr/ng-package.schema.json",
  "whitelistedNonPeerDependencies": [
    "angular",
    "rxjs",
    "ngrx"
  ],
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```

my `package.json` peerDependencies:

```json
"peerDependencies": {
  "@angular/core": "^6.0",
  "@angular/router": "^6.0",
  "@ngrx/effects": "^6.0",
  "@ngrx/router-store": "^6.0",
  "@ngrx/store": "^6.0",
  "rxjs": "^6.0"
}
```

Building output:

```sh
No name was provided for external module '@ngrx/effects' in output.globals – guessing 'effects'
No name was provided for external module '@ngrx/router-store' in output.globals – guessing 'routerStore
```

Normally when I use plain rollup config I define the globals like:

```js
// This works without warnings!
globals: {
  '@ngrx/store': 'ngrx.store',
  '@ngrx/router-store': 'ngrx.router-store',
  '@ngrx/effects': 'ngrx.effects',
  '@angular/core': 'ng.core',
  '@angular/router': 'ng.router',
  'rxjs': 'Rx',
  'rxjs/operators': 'Rx.operator'
}
```

How can solve this?

**Comment by benjamincharity** [comment]
@joseluisq 	I think what you're looking for is `umdModuleIds` under the `lib` key:

Example package.json:

```
  ...
  "ngPackage": {
    ...
    "lib": {
      ...
      "umdModuleIds": {
        "@angular/material": "ng.material",
        "@angular/cdk": "ng.cdk",
        ... // etc
      }
    },
    ...
```

**Comment by joseluisq** [comment]
@benjamincharity thanks It works now.
Alright! `"umdModuleIds"` is the equivalent to Rollup [`output.globals`](https://rollupjs.org/guide/en#output-globals) for `umd/iife` bundles.

[Resolving UMD Module Identifiers](https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers)

**Comment by rdhelms** [comment]
I wrote my rant in #932 - but since this issue has more recent activity, I thought I'd mention it here.

Basically, I'm just really concerned about the "official" answer being that we should always be using peerDependencies, where the implication is that using dependencies is "dangerous, bad, and generally a worse idea". I don't think this is actually always the case, and I really think the community would benefit from some more specific examples regarding the characteristics of a package that SHOULD belong in peerDependencies (a plugin - relies on something in the host, isn't directly `require`d, etc) vs. a package that should belong in dependencies (pretty much everything else...?).

I foresee "package update tornadoes" from apps having to update not just one package when a new version comes out, but all of its dependencies as well...and then all of their dependencies...and it just feels like a nightmare.

**Comment by xtianus79** [comment]
@alan-agius4  what is better add it to the ng-package.json or the package.json?

**Comment by alan-agius4** [comment]
It doesn’t make any difference. My personal preference is to keep configs for tools in their respective config files instead of putting each config in `package.json` I feel it gives a better separation of concern.
