### ISSUE TITLE
BUILD ERROR  @import url('~assets/...) wasn't found

### ISSUE THREAD

**Issue by liliom55** [dherges/ng-packagr#827]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description
I want to have a relative path from my package inside node_modules to a less file which is located in assets folder of my application. 

```
/node_modules
        ---------@myPackage/ui-date-picker
/src
       --------assets/styles/custom-theme.less'

```
'less' file of my application (ui-date-picker) that I want to package it, is some thing like this:

date-picker.component.less:
`@import url('~assets/styles/custom-theme');`

the assets folder is not supposed to be Inside this app. I want to refer to assets out of this package.
when I want to package my app I get this error:

```
BUILD ERROR
'~assets/styles/custom-theme.less' wasn't found.

```

when I buld it or serve it as 'aot', it is OK but when I want to package it, it's not possible. 
when I change it to :
`@import '../../assets/styles/custom-theme';`
is OK but the problem is, it refer to assets of Inside package not outside one.

I'll appreciate  If somebody let me know how to do it.
#### Version Information 

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: ^2.4.2
@angular/*: ^5.2.0
angular/cli: ~1.7.4
typescript: ~2.5.3
rxjs: ^5.5.6
node: v8.11.1
npm: 5.6.0
```

**Comment by alan-agius4** [comment]
I am not sure if I fully understand the issue here, but, a library shouldn't depend on an application, but rather vice-versa. 

When a library when you use `~assets` you are telling the library to locate that `less` or `sass` file from `node_modules` in this case it will be `node_modules/assets/styles/custom-theme`

https://github.com/webpack-contrib/sass-loader#imports
