### ISSUE TITLE
Add support for partial re-builds

### ISSUE THREAD

**Issue by dherges** [dherges/ng-packagr#828]
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

`ng-packagr watch` should only run the esm re-builds (incl. styles preprocessing), thus skipping fesm and umd bundling

#### How To Reproduce

n/a

#### Expected Behaviour

Relates to #635 #743 

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 3.x
```

**Comment by alan-agius4** [comment]
I think it’s best that all the re-build is complete, because for instance at the moment FESM is still required to by webpack in Angular CLI + flattening should be relatively fast.

**Comment by alan-agius4** [comment]
I think it’s best that all the re-build is complete, because for instance at the moment FESM is still required by webpack in Angular CLI + flattening should be relatively fast.

Also without running all the build transformation steps, for instance sourcemaps won’t get relocated / re-mapped with the current workflow unless they are inlined.

1) My idea on this is to have a watch ts compiler host, which caches the transpiled js output for each file, and when there is a file change it is removed from the cache. This is how Angular CLI are also doing the watch.  This will increase performance quite a lot as it will only transpile the changed files.

2) remove sourcemaps re-wiring and relocation adds extra steps which can be avoided or there are other solutions

3) remove downleveling, re-build esm’s async and be able to do partial re-compilation using the same watch compiler host logic. Have downleveling would increase complexity as one would require to have a separate watch host implantation.
