### ISSUE TITLE
Question: why not ship library sources instead of compiled files?

### ISSUE THREAD

**Issue by lwouis** [dherges/ng-packagr#831]
I can't find in the [APF](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/edit) spec or in any other place the reasoning behind not just shipping libraries as a collection of source files which can be compiled directly by the consumer project.

What am I missing? Why is it necessary to precompile the components to JS, add type files, and metadata?

**Comment by Tyler-V** [comment]
Good to know, wondered the same thing could solve a lot of the headaches I see to be having right now

**Comment by lwouis** [comment]
@alan-agius4 
> you are unable to compiler TypeScript code which sits in node_modules
Well you do it all the time with all libraries you use. You compile against `@angular/core` or `rxjs`, and those files live in `node_modules`. I assume a difference is made between typescript files, and javascript + typescript type files? It seems strange to me that such a distinction is made. I mean surely if it's technically possible to do one then it's possible to do the other.

I didn't find in either link you provided an explanation as to *why* it's not allowed. It seem to me like it would make distribution of typescript code so much easier.

Anyway this is unrelated to ng-packagr so i'll close the issue. Thanks for taking the time to answer! I really appreciate it!

**Comment by alan-agius4** [comment]
While technically it is possible, you are unable to compiler TypeScript from `node_modules` because Angular Compiler simply won't let you. But the fact there is an error is good and I believe it should stay there because shipping source code in `node_modules` is not optimal for various reason IMHO.

Some of them are;
1) Before using a library you need to compile it, and it might not work the same version of typescript you are using.
3) When you have a library you need to target as many people and many environments are possible, not everyone uses `TypeScript`, nor `webpack`.

This concept is quite similar to other languages as well, for instance if build in C# you compile before shipping it.

**Comment by mlc-mlapis** [comment]
@alan-agius4 ... but during AOT compilation `*.ngfactory.js` files are created so **it is always necessary to compile before using an Angular library** in fact.

**Comment by alan-agius4** [comment]
But it's a different compilation, And if you use a UMD bundle you don't need to compile.
